function [fitresult, gof] = kfit2(model_sigmas, model_k)
%KFIT2(MODEL_SIGMAS,MODEL_K)
%  Create a fit.
%
%  Data for 'k_fit2' fit:
%      X Input : model_sigmas
%      Y Output: model_k
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Dec-2018 02:07:09


%% Fit: 'k_fit2'.
[xData, yData] = prepareCurveData( model_sigmas, model_k );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'k_fit2' );
h = plot( fitresult, xData, yData );
legend( h, 'model_k vs. model_sigmas', 'k_fit2', 'Location', 'NorthEast' );
% Label axes
xlabel model_sigmas
ylabel model_k
grid on


