function [fitresult, gof] = kfit(k_best, sigma)
%KFIT(K_BEST,SIGMA)
%  Create a fit.
%
%  Data for 'k_fit' fit:
%      X Input : k_best
%      Y Output: sigma
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Dec-2018 01:07:23


%% Fit: 'k_fit'.
[xData, yData] = prepareCurveData( k_best, sigma );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'k_fit' );
h = plot( fitresult, xData, yData );
legend( h, 'sigma vs. k_best', 'k_fit', 'Location', 'NorthEast' );
% Label axes
xlabel k_best
ylabel sigma
grid on


